#!/bin/bash
echo "Creating HRMS databases..."
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE auth_db;"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE employee_db;"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE attendance_db;"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE students_db;"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE leave_db;"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE notification_db;"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE audit_db;"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE payroll_db;"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE onboarding_db;"
echo "All databases created!"
