import { test as base, type Page } from '@playwright/test'
import * as path from 'path'
import { mockTokens } from './jwt.factory'

type MockRole = keyof typeof mockTokens

/**
 * Inject a forged token into localStorage — bypasses the login form entirely.
 * Navigate to '/' first so localStorage is writable for the origin.
 */
export async function setMockedAuth(page: Page, role: MockRole) {
  await page.goto('/')
  await page.evaluate(
    ({ token }) => {
      localStorage.setItem('access_token', token)
      localStorage.setItem('refresh_token', 'mock-refresh-token')
      localStorage.setItem('company_name', 'Acme Corp')
      localStorage.setItem('selected_company_id', 'co-1')
    },
    { token: mockTokens[role] },
  )
}

/**
 * Path to a real storage state file generated by global-setup.ts.
 * Only available when E2E_REAL_AUTH=1 and the backend is running.
 */
export function realAuthStorageState(role: 'admin' | 'hr' | 'super-admin') {
  return path.join(__dirname, `../.auth/${role}.json`)
}

type AuthFixtures = {
  authedPage: Page     // admin role
  hrPage: Page         // hr role
  superAdminPage: Page // super_admin role
  employeePage: Page   // employee role
}

export const test = base.extend<AuthFixtures>({
  authedPage: async ({ page }, use) => {
    await setMockedAuth(page, 'admin')
    await use(page)
  },
  hrPage: async ({ page }, use) => {
    await setMockedAuth(page, 'hr')
    await use(page)
  },
  superAdminPage: async ({ page }, use) => {
    await setMockedAuth(page, 'superAdmin')
    await use(page)
  },
  employeePage: async ({ page }, use) => {
    await setMockedAuth(page, 'employee')
    await use(page)
  },
})

export { expect } from '@playwright/test'
