import {
  Activity,
  BarChart3,
  Bell,
  Building2,
  CalendarDays,
  CheckCircle2,
  Clock,
  FileSpreadsheet,
  Fingerprint,
  KeyRound,
  Settings,
  ShieldCheck,
  Upload,
  UserCog,
  Users,
  Wallet,
} from 'lucide-vue-next'
import type { DocBlock, DocModule, HelpFlow } from './helpTypes'
export const requiredBlocks = [
  'Overview',
  'Who Uses This',
  'Prerequisites',
  'Key Features',
  'How It Works (Conceptual Flow)',
  'Step-by-Step Usage',
  'Common Use Cases',
  'Edge Cases & Rules',
  'Errors & Troubleshooting',
  'Best Practices',
]

function blocks(items: Record<string, string[]>): DocBlock[] {
  return requiredBlocks.map(title => ({ title, bullets: items[title] ?? [] }))
}

export const modules: DocModule[] = [
  {
    id: 'authentication-login',
    title: 'Authentication & Login',
    summary: 'Secure entry point for Admin, HR, Manager, and Employee users, including token-based sessions and role-aware routing.',
    category: 'Access',
    icon: KeyRound,
    audience: ['Admin', 'HR', 'Employee', 'Manager'],
    navTabs: [{ label: 'Open Login', tab: 'dashboard' }, { label: 'My Profile', tab: 'profile' }],
    blocks: blocks({
      'Overview': [
        'This module verifies user identity before allowing access to company HR data.',
        'It exists to protect employee records, payroll information, attendance logs, and policy configuration from unauthorized access.',
        'Business value: one trusted sign-in flow reduces manual account support and gives HR confidence that each user sees only the right tools.',
      ],
      'Who Uses This': [
        'Admins use it to access company setup, employees, payroll, and system configuration.',
        'HR users use it for daily workforce operations such as attendance review, leave administration, and employee updates.',
        'Employees use it to access their profile, attendance actions, leave balances, payslips, and requests when those portals are enabled.',
        'Managers use it to review team requests and operational dashboards when manager permissions are assigned.',
      ],
      'Prerequisites': [
        'The user must have an active account or a valid employee invite.',
        'The company must be selected or assigned for users who belong to multiple companies.',
        'Browser storage must allow session tokens so the app can keep the user signed in during navigation.',
        'Permissions must be mapped to the role: admin, hr, manager, employee, or super admin portal access where applicable.',
      ],
      'Key Features': [
        'Email and password based login.',
        'JWT session validation before protected pages load.',
        'Role-based route restrictions for sensitive modules such as Payroll and Onboarding.',
        'Automatic logout when a token expires or is invalid.',
        'Profile page for checking account identity, role, department, branch, and active session status.',
      ],
      'How It Works (Conceptual Flow)': [
        'User enters credentials, the backend returns an access token, and the dashboard stores it for authenticated API calls.',
        'The router checks the token before loading protected pages; invalid or expired sessions are redirected to login.',
        'Role claims decide whether a user can access HR-only areas such as Payroll or Onboarding.',
        'Employee profile data is loaded after login and connects the signed-in user to department, branch, designation, and employment status.',
      ],
      'Step-by-Step Usage': [
        'Open the HRMS login page.',
        'Enter the registered email address and password.',
        'Click Sign In; the expected result is navigation to Onboarding or Dashboard depending on company setup status.',
        'If prompted to select a company, choose the company you want to manage; the expected result is company-specific navigation and data.',
        'Open My Profile from the sidebar to verify role, department, branch, and session status.',
        'Click Sign Out when finished; the expected result is token removal and return to the login page.',
      ],
      'Common Use Cases': [
        'A new employee accepts an invite and signs in for the first time.',
        'An HR executive logs in each morning to review attendance exceptions and leave requests.',
        'An admin signs in to complete company setup before go-live.',
        'A user signs out on a shared device to prevent accidental access.',
      ],
      'Edge Cases & Rules': [
        'Expired tokens are rejected and the user is sent back to login.',
        'Super admin users are blocked from the HR dashboard and must use the Super Admin Portal.',
        'Role-restricted pages redirect unauthorized users to Dashboard.',
        'If the employee profile is missing, the UI falls back to the email address from the token.',
      ],
      'Errors & Troubleshooting': [
        'Invalid credentials: confirm email spelling, password, and whether the account invite has been accepted.',
        'Redirect loop: clear browser storage, sign in again, and verify the backend returns a valid role claim.',
        'Cannot access Payroll: confirm the user role is admin or hr and the route permissions include that role.',
        'Company data not visible: confirm selected_company_id and selected company access are valid.',
      ],
      'Best Practices': [
        'Give each person their own login; never share HR or payroll accounts.',
        'Review user roles after promotions, transfers, or exits.',
        'Ask employees to complete first login before their first attendance day.',
        'Use sign out on shared computers and after payroll work.',
      ],
    }),
  },
  {
    id: 'company-setup-onboarding',
    title: 'Company Setup / Onboarding',
    summary: 'Guided first-time setup that prepares a company for employees, attendance, leave, overtime, and payroll.',
    category: 'Setup',
    icon: Building2,
    audience: ['Admin', 'HR'],
    navTabs: [{ label: 'Open Onboarding', tab: 'dashboard' }, { label: 'Departments', tab: 'departments' }],
    blocks: blocks({
      'Overview': [
        'This module turns a blank company workspace into a usable HRMS environment.',
        'It exists because employee operations depend on consistent setup data such as departments, branches, grades, shifts, and policies.',
        'Business value: clean onboarding prevents downstream errors in imports, attendance, leave balances, payroll calculations, and reports.',
      ],
      'Who Uses This': [
        'Admins own the complete setup and final go-live decision.',
        'HR users usually configure HR setup, employee records, attendance readiness, and leave rules.',
        'Finance or payroll admins may help configure salary structures, statutory settings, and tax profiles.',
      ],
      'Prerequisites': [
        'An admin or HR account with access to the company workspace.',
        'A confirmed company name and primary operating locations.',
        'A list of departments, branches, designations, employment types, grades, employee groups, and initial employee data.',
        'Policy decisions for attendance, leave, overtime, payroll cycle, and holiday calendars.',
      ],
      'Key Features': [
        'Step-by-step setup progress tracking.',
        'Template-based onboarding where available.',
        'Required setup prompts before attendance and payroll are used.',
        'Deep links from guide steps into the matching HRMS module.',
        'Completion state so admins can see what remains before launch.',
      ],
      'How It Works (Conceptual Flow)': [
        'Company setup creates the master data used by every other module.',
        'Departments and branches are assigned to employees; employees are assigned shifts and policies; attendance and leave then generate records; payroll consumes employee salary data and attendance or leave impacts.',
        'The recommended order is HR Setup, shift locations, shift types, employees, shift schedules, leave setup, overtime setup, then payroll setup.',
        'Skipping a setup item usually does not break the UI, but it creates missing dependencies later.',
      ],
      'Step-by-Step Usage': [
        'Open the onboarding banner or onboarding page after first login.',
        'Review each setup step and identify which data must be prepared before entry.',
        'Create HR setup records: departments, branches, designations, employment types, grades, and employee groups.',
        'Create shift locations and shift types before adding attendance employees.',
        'Add employees manually or through Bulk Import.',
        'Assign shifts, leave policies, and payroll settings before go-live.',
        'Mark steps complete only after the related module has been verified with at least one real record.',
      ],
      'Common Use Cases': [
        'A new company is launched in HRMS for the first time.',
        'An existing company adds a new branch and needs setup data before employees transfer there.',
        'HR imports the first workforce list and wants to avoid validation failures.',
        'An admin prepares payroll after employee and salary setup is complete.',
      ],
      'Edge Cases & Rules': [
        'Lookup names used in CSV imports must match setup records exactly.',
        'Employees should not be imported before departments, branches, designations, and employment types exist.',
        'Attendance is not production-ready until each attendance employee has one active schedule assignment and one valid location.',
        'Payroll should not be run until salary structure and tax profile requirements are complete.',
      ],
      'Errors & Troubleshooting': [
        'Onboarding step will not complete: confirm the target module contains saved records and refresh status.',
        'Bulk import lookup failures: fix spelling differences between CSV values and HR Setup names.',
        'Attendance warning after setup: check missing shift type, missing location, or overlapping assignments.',
        'Payroll excludes employees: confirm salary structure, joining date, active status, and tax profile.',
      ],
      'Best Practices': [
        'Use a small pilot group before importing the full workforce.',
        'Name setup records in plain business language that HR and employees already use.',
        'Document policy decisions before configuration so admins do not encode temporary assumptions.',
        'Revisit onboarding checks after major changes such as new branch, new leave year, or payroll policy update.',
      ],
    }),
  },
  {
    id: 'employee-management',
    title: 'Employee Management',
    summary: 'Central employee directory for identity, employment details, contact data, salary inputs, account status, and invitations.',
    category: 'Core HR',
    icon: Users,
    audience: ['Admin', 'HR', 'Manager'],
    navTabs: [{ label: 'Employee Directory', tab: 'employees' }, { label: 'Bulk Import', tab: 'employees-import-queue' }],
    blocks: blocks({
      'Overview': [
        'This module stores the official employee profile used across the HRMS.',
        'It exists to provide one authoritative record for employee identity, job details, reporting structure, payroll attributes, and portal access.',
        'Business value: accurate employee records reduce payroll errors, attendance mismatches, leave allocation issues, and manual HR follow-up.',
      ],
      'Who Uses This': [
        'Admins create, edit, delete, and audit employee records.',
        'HR users maintain day-to-day profile updates and invite employees to the portal.',
        'Managers may view team member information when their permissions allow it.',
        'Employees view their own profile and account details through self-service when enabled.',
      ],
      'Prerequisites': [
        'Departments, branches, designations, employment types, grades, and groups should exist before creating employees.',
        'Each employee needs a unique email address for portal login and invites.',
        'Payroll usage requires joining salary, salary structure, and tax profile fields where applicable.',
        'Attendance usage requires active status plus schedule assignment after employee creation.',
      ],
      'Key Features': [
        'Employee directory with search, filters, status badges, and bulk actions.',
        'Employee drawer for creating or editing personal, contact, joining, department, salary, education, experience, emergency, and exit details.',
        'Employee profile panel for viewing complete HR data.',
        'Portal invite and resend invite actions.',
        'Bulk import queue for large employee onboarding.',
      ],
      'How It Works (Conceptual Flow)': [
        'Employee profile is the central entity connected to department, branch, designation, employment type, grade, and reporting manager.',
        'Attendance connects employee to schedule assignment and check-in records.',
        'Leave connects employee to leave policy assignments, allocations, balances, and ledger entries.',
        'Payroll connects employee to salary structure, tax profile, payroll run, payslip, and payment status.',
      ],
      'Step-by-Step Usage': [
        'Go to Employees > Employee Directory.',
        'Click Add Employee to open the employee drawer.',
        'Complete personal and contact fields; expected result is a profile with unique identity details.',
        'Complete employment fields: department, branch, designation, employment type, grade, joining date, and reporting manager.',
        'Add salary and statutory fields if payroll will be used.',
        'Click Save; expected result is a new active employee in the directory.',
        'Send or resend the employee portal invite from the employee row or profile.',
        'Open the profile to verify all linked setup values are correct.',
      ],
      'Common Use Cases': [
        'Add a new hire before their joining date.',
        'Update an employee after transfer to another department or branch.',
        'Resend login invitation to employees who have not registered.',
        'Mark an employee exited and preserve their history for reports.',
      ],
      'Edge Cases & Rules': [
        'Email must be unique across portal accounts.',
        'Inactive or exited employees should not be included in new schedule assignments or payroll runs unless policy requires final settlement.',
        'Changing department or branch may require updated leave policy, schedule assignment, manager access, and reporting filters.',
        'Deleting employees can affect audit history; prefer inactive or exited status when records are needed for compliance.',
      ],
      'Errors & Troubleshooting': [
        'Employee save fails: check required fields, invalid email, duplicate employee code, and missing lookup selections.',
        'Invite not received: resend invite, verify email spelling, and ask the employee to check spam or blocked mail rules.',
        'Employee missing from attendance: confirm active status and schedule assignment.',
        'Employee missing from payroll: confirm salary setup, tax profile, employment status, and payroll cycle eligibility.',
      ],
      'Best Practices': [
        'Create setup values before adding employees so profile fields stay consistent.',
        'Use employee codes that match finance or ERP systems.',
        'Review new employee profiles before sending invites.',
        'Use bulk import for large batches and manual creation for sensitive or executive records.',
      ],
    }),
  },
  {
    id: 'department-management',
    title: 'Department Management',
    summary: 'Organizational structure for grouping employees, reporting, permissions, leave policies, overtime scope, and analytics.',
    category: 'Core HR',
    icon: UserCog,
    audience: ['Admin', 'HR', 'Manager'],
    navTabs: [{ label: 'Departments', tab: 'departments' }, { label: 'Designations', tab: 'designations' }],
    blocks: blocks({
      'Overview': [
        'This module defines the formal departments used in employee profiles.',
        'It exists so workforce data can be grouped by business function such as HR, Finance, Engineering, Sales, or Operations.',
        'Business value: department structure powers cleaner reporting, policy assignment, manager review, and workforce planning.',
      ],
      'Who Uses This': [
        'Admins create the company department hierarchy.',
        'HR users maintain department names, parent departments, and employee assignment accuracy.',
        'Managers consume department-filtered views for their teams.',
      ],
      'Prerequisites': [
        'Company workspace must exist.',
        'Admin or HR permission is required for create, edit, and delete actions.',
        'If using parent departments, decide hierarchy before mass employee assignment.',
        'Designations and employee groups can be created after or alongside departments.',
      ],
      'Key Features': [
        'Create departments with optional description and reporting hierarchy.',
        'Edit department details when business naming changes.',
        'Use departments in employee profile assignment.',
        'Filter employees, attendance, overtime, and reports by department.',
        'Scope overtime policies or leave rules by department where supported.',
      ],
      'How It Works (Conceptual Flow)': [
        'Department is a lookup record connected to many employee profiles.',
        'Employee -> department relationship is used by attendance summaries, payroll review, leave reports, and manager visibility.',
        'When an employee changes department, future operations should use the new department while historical records remain auditable.',
        'Department-level policies apply to employees assigned to that department unless employee-specific rules override them.',
      ],
      'Step-by-Step Usage': [
        'Go to HR Setup > Departments.',
        'Click Add Department.',
        'Enter the department name exactly as HR will use it in employee records and imports.',
        'Add description or parent department if the UI supports it.',
        'Click Save; expected result is a department row available in employee forms and filters.',
        'Assign employees to the department from Employees > Employee Directory.',
      ],
      'Common Use Cases': [
        'Create departments during first company setup.',
        'Add a new business unit after company restructuring.',
        'Move employees between departments after transfer.',
        'Run attendance or payroll review by department.',
      ],
      'Edge Cases & Rules': [
        'Avoid duplicate names with minor spelling changes because imports and filters become unreliable.',
        'Do not delete a department if active employees still belong to it; reassign employees first.',
        'Department changes may affect policy scope and manager dashboards.',
        'Historical records should be interpreted with the employee department at the time of reporting when available.',
      ],
      'Errors & Troubleshooting': [
        'Department missing from employee form: refresh setup data and confirm the department was saved.',
        'CSV import cannot find department: update CSV value to exactly match the department name.',
        'Reports look wrong: check employees assigned to old or misspelled departments.',
        'Cannot delete department: remove employee dependencies or mark the department inactive if supported.',
      ],
      'Best Practices': [
        'Use stable department names and avoid abbreviations unless the business already uses them.',
        'Review department assignments monthly before payroll and analytics reporting.',
        'Keep hierarchy shallow enough for HR users to understand.',
        'Create employee groups for policy exceptions instead of overloading departments.',
      ],
    }),
  },
  {
    id: 'attendance-system',
    title: 'Attendance System',
    summary: 'Tracks daily clock-in, clock-out, geofence validation, work hours, late marks, missed punch-outs, and corrections.',
    category: 'Time',
    icon: Clock,
    audience: ['Admin', 'HR', 'Employee', 'Manager'],
    navTabs: [
      { label: 'Records', tab: 'attendance-records' },
      { label: 'Check-ins', tab: 'attendance-checkins' },
      { label: 'Adjustments', tab: 'attendance-requests' },
    ],
    blocks: blocks({
      'Overview': [
        'This module records when employees start and end work and calculates attendance outcomes.',
        'It exists to create a reliable time record for HR operations, payroll inputs, compliance, and manager visibility.',
        'Business value: accurate attendance reduces manual timesheets, supports overtime rules, and highlights attendance exceptions quickly.',
      ],
      'Who Uses This': [
        'Employees clock in, add shift context, and clock out from the employee app or allowed attendance screen.',
        'HR monitors daily records, resolves missed punch-outs, and approves correction requests.',
        'Admins configure shifts, locations, and attendance policies.',
        'Managers review team attendance when permission is enabled.',
      ],
      'Prerequisites': [
        'Employees must be active and invited to the portal.',
        'Shift locations must exist when geofence attendance is used.',
        'Shift types must define start time, end time, grace period, break minutes, and night shift behavior.',
        'Each attendance employee needs one active schedule assignment for the work date.',
      ],
      'Key Features': [
        'Daily attendance records with clock-in and clock-out times.',
        'GPS/geofence validation through shift locations.',
        'Late, absent, present, half-day, and missed punch-out review patterns.',
        'Attendance adjustment requests for corrections.',
        'Bulk attendance and biometric import paths for legacy devices.',
      ],
      'How It Works (Conceptual Flow)': [
        'Employee -> schedule assignment -> shift type + location -> attendance record.',
        'At clock-in, the system checks active assignment, current time, and location rules.',
        'At clock-out, work hours are calculated from punch times minus configured breaks and adjusted by night-shift rules where applicable.',
        'Overtime records can be generated when actual work exceeds policy thresholds.',
      ],
      'Step-by-Step Usage': [
        'Go to Attendance > Check-ins or have the employee open Attendance in the employee app.',
        'Employee taps Clock In; expected result is an open attendance record with clock-in time and location evidence.',
        'During the day, HR can open Attendance > Attendance Records to monitor active and completed records.',
        'Employee taps Clock Out at day end; expected result is final work hours and attendance status calculation.',
        'If a punch is wrong, employee or HR opens Attendance > Attendance Adjustments and submits the correction with reason.',
        'HR reviews the request and approves or rejects it; expected result is corrected record history with notes.',
      ],
      'Common Use Cases': [
        'Track office attendance for a standard 9:00 to 18:00 shift.',
        'Handle missed clock-out requests the next morning.',
        'Import biometric punch data for employees using physical attendance devices.',
        'Review late arrivals before payroll cutoff.',
      ],
      'Edge Cases & Rules': [
        'Employees without active schedule assignment cannot be evaluated correctly for late, work hours, or overtime.',
        'Night shifts must be marked as night shift so end time after midnight is interpreted correctly.',
        'One employee should not have overlapping active assignments for the same date.',
        'Offline punch actions should sync in chronological order when network returns if the employee app supports offline queueing.',
      ],
      'Errors & Troubleshooting': [
        'Missing schedule assignment: create or correct the employee assignment in Shifts > Shift Schedules.',
        'Outside geofence: confirm employee is at the correct site and shift location coordinates/radius are accurate.',
        'Duplicate open record: close or correct the existing record before adding another punch.',
        'Wrong hours: check break minutes, clock-out time, night shift flag, and manual corrections.',
      ],
      'Best Practices': [
        'Resolve missed punch-outs daily instead of waiting for payroll cutoff.',
        'Use correction notes for every manual edit.',
        'Review attendance setup health before enabling employee self-service.',
        'Pilot geofence radius with real devices at each office entrance.',
      ],
    }),
  },
  {
    id: 'face-recognition-attendance',
    title: 'Face Recognition Attendance',
    summary: 'Optional biometric attendance layer that verifies employee identity at punch time when face recognition is enabled.',
    category: 'Time',
    icon: Fingerprint,
    audience: ['Admin', 'HR', 'Employee'],
    navTabs: [{ label: 'Check-ins', tab: 'attendance-checkins' }, { label: 'Upload Biometric', tab: 'attendance-upload' }],
    blocks: blocks({
      'Overview': [
        'This module adds identity verification to attendance by comparing a live face capture with an enrolled employee profile.',
        'It exists to reduce buddy punching and improve confidence that the person recording attendance is the assigned employee.',
        'Business value: stronger attendance integrity, fewer disputes, and better compliance for high-control work sites.',
      ],
      'Who Uses This': [
        'Admins enable the feature and manage biometric policy.',
        'HR enrolls employees, monitors failed verification attempts, and handles exceptions.',
        'Employees complete face enrollment and use face capture during clock-in or clock-out.',
      ],
      'Prerequisites': [
        'Face recognition must be enabled by product configuration or backend feature flag.',
        'Employees must have active profiles and consent workflow handled according to company policy and local law.',
        'Device camera permission must be granted in the browser or PWA.',
        'Attendance setup must already be valid: employee, shift assignment, shift type, and location rules.',
      ],
      'Key Features': [
        'Employee face enrollment when enabled.',
        'Camera-based verification at attendance punch time.',
        'Failed match handling and HR exception review.',
        'Audit trail of verification result attached to attendance actions where supported.',
        'Fallback to HR-approved manual correction when biometric capture cannot be completed.',
      ],
      'How It Works (Conceptual Flow)': [
        'Employee profile stores or references an approved face template according to system configuration.',
        'At punch time, the app captures a live image and asks the backend to compare it with the enrolled identity.',
        'Attendance is accepted only when identity, assignment, time, and location checks pass.',
        'If face verification fails, the system should block or flag the punch depending on configured policy.',
      ],
      'Step-by-Step Usage': [
        'Admin confirms face recognition is enabled for the company.',
        'HR opens the employee profile and starts enrollment if the enrollment UI is available.',
        'Employee grants camera permission and completes the required capture steps.',
        'Employee opens Attendance and taps Clock In.',
        'When prompted, employee aligns face in camera and submits capture; expected result is verified attendance if the match passes.',
        'HR reviews failed or exception records from Attendance > Check-ins or Attendance Records.',
      ],
      'Common Use Cases': [
        'Factory or site attendance where identity assurance is required.',
        'High-volume check-in points with shared devices.',
        'Audit investigation of disputed attendance records.',
        'Temporary fallback when biometric device import is unavailable.',
      ],
      'Edge Cases & Rules': [
        'Low light, masks, camera blur, or changed appearance can cause false rejection.',
        'Face data handling must follow company consent, retention, and privacy policy.',
        'Employees without enrollment should be blocked or routed to HR exception flow based on policy.',
        'If the feature is disabled, users should use standard geofence or biometric import attendance.',
      ],
      'Errors & Troubleshooting': [
        'Camera permission denied: enable camera permission for the site or installed PWA and retry.',
        'Face not detected: improve lighting, clean camera lens, and keep the full face in frame.',
        'Verification failed: re-enroll employee if HR confirms the correct person attempted attendance.',
        'Feature not visible: confirm the face recognition feature flag and backend endpoint availability.',
      ],
      'Best Practices': [
        'Document consent and retention policy before enrollment.',
        'Enroll employees in consistent lighting with a clear front-facing capture.',
        'Keep a manual exception path for accessibility, camera failure, and approved special cases.',
        'Monitor failed verification patterns to improve setup quality.',
      ],
    }),
  },
  {
    id: 'leave-management',
    title: 'Leave Management',
    summary: 'Configures leave periods, holiday lists, leave types, policies, allocations, balances, block lists, comp-off, encashment, and ledger history.',
    category: 'Absence',
    icon: CalendarDays,
    audience: ['Admin', 'HR', 'Employee', 'Manager'],
    navTabs: [
      { label: 'Leave Types', tab: 'leave-types' },
      { label: 'Policies', tab: 'leave-policies' },
      { label: 'Balances', tab: 'leave-balance' },
    ],
    blocks: blocks({
      'Overview': [
        'This module manages employee time off from policy definition through balance tracking and audit history.',
        'It exists to standardize leave eligibility, approvals, holidays, carry-forward, block periods, comp-off, and encashment.',
        'Business value: transparent balances reduce disputes and give HR reliable absence planning data.',
      ],
      'Who Uses This': [
        'Admins configure leave years, policies, holiday lists, and special rules.',
        'HR allocates leave, reviews balances, handles encashment, and audits ledger entries.',
        'Employees submit leave requests and view balances when self-service is enabled.',
        'Managers approve or review team leave where workflow permits.',
      ],
      'Prerequisites': [
        'Employee records must exist and be active.',
        'Leave periods must be created for the relevant year or fiscal cycle.',
        'Leave types and holiday lists must be configured before policies are assigned.',
        'Policy assignments and allocations must exist before employees can consume balances.',
      ],
      'Key Features': [
        'Leave periods for annual or fiscal cycles.',
        'Holiday lists and attendance holiday calendars.',
        'Leave types such as annual, sick, casual, maternity, paternity, unpaid, and comp-off.',
        'Leave policies with carry-forward, accrual, maximum days, and approval rules.',
        'Allocations, balances, block lists, encashments, compensatory leave, and leave ledger.',
      ],
      'How It Works (Conceptual Flow)': [
        'Leave period contains the time range for balances.',
        'Leave type defines the category; policy defines rules; assignment connects policy to employee or group; allocation grants days.',
        'Employee leave requests consume available balance and create ledger entries.',
        'Holidays and block lists adjust eligibility and availability according to policy.',
      ],
      'Step-by-Step Usage': [
        'Go to Leave > Leave Periods and create the annual or fiscal period.',
        'Go to Leave > Holiday Lists and create company holidays for that period.',
        'Go to Leave > Leave Types and create each leave category.',
        'Go to Leave > Leave Policies and define entitlement, carry-forward, accrual, and approval rules.',
        'Go to Leave > Policy Assignments and assign policies to employees or groups.',
        'Go to Leave > Leave Allocations and grant opening balances.',
        'Open Leave Balances and verify every employee has expected available days.',
      ],
      'Common Use Cases': [
        'Allocate annual leave at the start of the year.',
        'Block leave during payroll cutoff, audit week, or production freeze.',
        'Grant compensatory leave for approved holiday work.',
        'Process leave encashment for eligible employees.',
      ],
      'Edge Cases & Rules': [
        'Employees without allocation may have zero balance even if a policy exists.',
        'Carry-forward should be capped according to company policy.',
        'Block lists may restrict selected leave types, employees, or date ranges.',
        'Leave ledger should remain append-only in spirit: corrections should be auditable rather than silently overwritten.',
      ],
      'Errors & Troubleshooting': [
        'Employee cannot request leave: check policy assignment, active period, allocation, and balance.',
        'Wrong balance: review allocation, carry-forward, approved requests, encashment, and ledger entries.',
        'Holiday counted as leave: confirm holiday list assignment and date coverage.',
        'Policy not applying: confirm employee group, department, effective date, and assignment priority.',
      ],
      'Best Practices': [
        'Complete leave setup before inviting employees to request leave.',
        'Use employee groups for policy differences such as probation, field staff, or leadership.',
        'Review balances before monthly payroll and year-end rollover.',
        'Keep leave type names simple and recognizable.',
      ],
    }),
  },
  {
    id: 'payroll-system',
    title: 'Payroll System',
    summary: 'Runs payroll cycles, calculates earnings and deductions, manages salary structures, tax profiles, reports, and payslips.',
    category: 'Finance',
    icon: Wallet,
    audience: ['Admin', 'HR', 'Employee'],
    navTabs: [{ label: 'Open Payroll', tab: 'payroll' }],
    blocks: blocks({
      'Overview': [
        'This module manages compensation processing from salary setup to payroll run review and reporting.',
        'It exists to convert employee salary data, tax rules, benefits, deductions, attendance, and leave inputs into accurate net pay.',
        'Business value: repeatable payroll cycles reduce finance workload and improve employee trust in payslips.',
      ],
      'Who Uses This': [
        'Admins configure payroll settings, salary structures, tax profiles, and final approval rules.',
        'HR reviews employee eligibility, joining or exit impacts, and payroll inputs.',
        'Employees may view payslips when self-service access is enabled.',
        'Finance users may export reports and payment files if assigned access.',
      ],
      'Prerequisites': [
        'Employee profiles must include active status, joining date, salary details, and payroll eligibility.',
        'Salary structures and tax profiles must be configured before payroll calculation.',
        'Attendance, leave, overtime, and unpaid leave data should be reviewed before payroll cutoff.',
        'Only admin or HR roles can access the current Payroll route in this dashboard.',
      ],
      'Key Features': [
        'Payroll run creation by period.',
        'Employee gross, deduction, and net salary calculation.',
        'Salary structure settings for basic, HRA, allowances, PF, ESI, and other components.',
        'Tax profile settings and statutory deduction support.',
        'Reports and payslip generation.',
      ],
      'How It Works (Conceptual Flow)': [
        'Employee salary data and salary structure define earnings components.',
        'Tax profile and statutory settings define deductions.',
        'Attendance, leave without pay, overtime, and joining or exit dates can affect payable days and adjustments.',
        'Payroll run calculates results, HR reviews exceptions, admin finalizes, and reports or payslips become available.',
      ],
      'Step-by-Step Usage': [
        'Go to Payroll.',
        'Open Settings and create salary structures and tax profiles before the first run.',
        'Assign salary structure and tax profile to employees from their profile or payroll setup flow.',
        'Click New Payroll Run and choose the month or pay period.',
        'Review included employees, gross salary, deductions, overtime, unpaid leave, and net pay.',
        'Fix employee setup issues and recalculate if required.',
        'Finalize the run; expected result is a locked payroll period with reports and payslips available.',
      ],
      'Common Use Cases': [
        'Run monthly payroll after attendance cutoff.',
        'Generate payslips for all employees in a period.',
        'Review payroll reports by department or employee.',
        'Exclude employees missing required salary or tax setup until corrected.',
      ],
      'Edge Cases & Rules': [
        'Employees without salary structure or tax profile may be excluded or flagged.',
        'New joiners and exits may require pro-rated pay.',
        'Finalized payroll should be locked from casual edits; corrections should happen through adjustment flow or next-cycle correction.',
        'Overtime and unpaid leave should be approved before payroll is calculated.',
      ],
      'Errors & Troubleshooting': [
        'Employee missing from run: check active status, joining date, payroll eligibility, salary structure, and tax profile.',
        'Wrong net pay: review salary components, deductions, attendance days, leave without pay, and overtime inputs.',
        'Report disabled: confirm a payroll run is selected and finalized if required.',
        'Cannot access Payroll: verify the user role is admin or HR.',
      ],
      'Best Practices': [
        'Use a payroll checklist before every cutoff.',
        'Resolve attendance and leave exceptions before creating the final payroll run.',
        'Keep salary structures versioned by effective date when policies change.',
        'Export and archive payroll reports after finalization.',
      ],
    }),
  },
  {
    id: 'calendar-events',
    title: 'Calendar & Events',
    summary: 'Workspace calendar for team events, shared schedules, holiday visibility, task planning, and Google calendar integrations where connected.',
    category: 'Collaboration',
    icon: CalendarDays,
    audience: ['Admin', 'HR', 'Employee', 'Manager'],
    navTabs: [{ label: 'Workspace Calendar', tab: 'workspace-calendar' }, { label: 'Team Hub', tab: 'workspace-hub' }],
    blocks: blocks({
      'Overview': [
        'This module provides a shared calendar for HR, team events, planning, and workspace coordination.',
        'It exists so workforce events are visible beside tasks, notes, and operational schedules.',
        'Business value: teams coordinate holidays, meetings, reminders, and work events without relying only on external calendars.',
      ],
      'Who Uses This': [
        'Admins configure workspace settings and integration behavior.',
        'HR publishes company events, onboarding sessions, training, and policy deadlines.',
        'Managers plan team activities and review availability.',
        'Employees view events relevant to their workspace.',
      ],
      'Prerequisites': [
        'A workspace must exist and the user must be a workspace member.',
        'Calendar permissions are required for creating, editing, or deleting events.',
        'Google integration requires a connected Google account and selected calendars.',
        'Holiday visibility requires holiday lists or holiday calendars to be configured in leave or attendance modules.',
      ],
      'Key Features': [
        'Workspace calendar view.',
        'Event creation, details, and updates.',
        'Calendar search service support.',
        'Google calendar connection and selected calendar sync where enabled.',
        'Relationship with task board, notes, and team hub.',
      ],
      'How It Works (Conceptual Flow)': [
        'Workspace contains members, calendars, events, tasks, and notes.',
        'Events belong to a calendar and can be displayed in calendar views and team hub summaries.',
        'External calendar integrations add connected calendar events to the workspace context where configured.',
        'Holiday and leave events provide planning context but should not replace official leave or attendance records.',
      ],
      'Step-by-Step Usage': [
        'Go to Workspace > Calendar.',
        'Choose the calendar or date range you want to view.',
        'Click the add event action if you have permission.',
        'Enter title, date, time, attendees, location or meeting details, and notes.',
        'Save; expected result is an event visible in the calendar and relevant workspace views.',
        'Open an event to edit details or review history when needed.',
      ],
      'Common Use Cases': [
        'Publish training sessions for new employees.',
        'Add HR policy deadlines and payroll cutoff reminders.',
        'Plan team meetings around holidays and leave visibility.',
        'Connect Google calendars for shared planning.',
      ],
      'Edge Cases & Rules': [
        'External calendar sync depends on authorization and selected calendars.',
        'Deleting an event should not delete official attendance, leave, or payroll data.',
        'Timezone differences can affect displayed event times for remote teams.',
        'Users without workspace membership may not see workspace events.',
      ],
      'Errors & Troubleshooting': [
        'Calendar appears empty: confirm selected calendars, workspace membership, and date range.',
        'Google events missing: reconnect Google integration and confirm selected calendars.',
        'Cannot create event: verify workspace role and calendar permission.',
        'Wrong time shown: check browser timezone, event timezone, and user locale settings.',
      ],
      'Best Practices': [
        'Use calendar events for planning and reminders, not as substitutes for official HR transactions.',
        'Name events with clear audience and purpose.',
        'Keep payroll, onboarding, and compliance deadlines visible to HR teams.',
        'Review connected calendars periodically to remove stale access.',
      ],
    }),
  },
  {
    id: 'notifications-system',
    title: 'Notifications System',
    summary: 'Operational alerts and user-facing prompts for invites, approvals, reminders, attendance issues, payroll events, and system status.',
    category: 'Communication',
    icon: Bell,
    audience: ['Admin', 'HR', 'Employee', 'Manager'],
    blocks: blocks({
      'Overview': [
        'This module informs users when action or awareness is required.',
        'It exists to reduce missed approvals, pending setup tasks, attendance exceptions, payroll deadlines, and invite failures.',
        'Business value: timely notifications keep HR processes moving without manual chasing.',
      ],
      'Who Uses This': [
        'Admins receive setup, system, and policy-impact notifications.',
        'HR receives attendance exceptions, leave or overtime requests, import results, and onboarding alerts.',
        'Employees receive invites, request status changes, attendance reminders, and payslip availability where enabled.',
        'Managers receive team approval prompts when assigned.',
      ],
      'Prerequisites': [
        'User accounts and role permissions must exist.',
        'Notification channels such as in-app, email, or push must be enabled by product configuration.',
        'Employees need valid email addresses for invite and email notifications.',
        'Relevant modules must emit events such as request submitted, payroll finalized, or import completed.',
      ],
      'Key Features': [
        'In-app status messages and banners.',
        'Employee invite and resend invite notifications.',
        'Approval prompts for leave, overtime, and attendance adjustments.',
        'Import result messages for success or failure.',
        'Operational warnings for missing setup, missed punch-outs, and sync issues.',
      ],
      'How It Works (Conceptual Flow)': [
        'A module action creates an event such as invite sent, request submitted, attendance failed, or payroll finalized.',
        'The notification system maps the event to recipients based on role, employee relationship, or workspace membership.',
        'Users see the message in the relevant UI area or channel.',
        'Some notifications require action; others are informational audit signals.',
      ],
      'Step-by-Step Usage': [
        'Perform a workflow that emits a notification, such as sending an employee invite.',
        'Watch for success or error feedback in the current panel.',
        'For approvals, open the relevant module such as Attendance Adjustments, Leave Requests, or Overtime Requests.',
        'Review the request, take action, and confirm the status message updates.',
        'For import notifications, open Bulk Import and review job status and error files.',
      ],
      'Common Use Cases': [
        'Notify employee after HR sends a portal invite.',
        'Alert HR about missed punch-outs or failed attendance sync.',
        'Inform requester when leave or overtime is approved or rejected.',
        'Show payroll run readiness or report generation status.',
      ],
      'Edge Cases & Rules': [
        'Notifications should not grant access; permissions still control what the user can open.',
        'Duplicate notifications may occur if a user retries the same action; the latest status should be trusted.',
        'Email delivery can fail outside the app due to spam, invalid address, or provider blocks.',
        'Sensitive payroll notifications should avoid exposing net pay in broad channels.',
      ],
      'Errors & Troubleshooting': [
        'Invite notification not received: verify employee email and resend invite.',
        'Approval status not updated: refresh the module and confirm the request action was saved.',
        'Import notification says failed: open the error CSV, fix rows, and re-upload.',
        'Too many alerts: review notification preferences or workflow duplication where settings exist.',
      ],
      'Best Practices': [
        'Keep notification text action-oriented and specific.',
        'Use module dashboards for final truth, not email alone.',
        'Resolve daily exception notifications before payroll or compliance review.',
        'Avoid sending payroll or disciplinary details through broad notification channels.',
      ],
    }),
  },
  {
    id: 'reports-analytics',
    title: 'Reports & Analytics',
    summary: 'Dashboards, exports, payroll reports, overtime summaries, attendance metrics, leave ledger analysis, and workforce insights.',
    category: 'Insights',
    icon: BarChart3,
    audience: ['Admin', 'HR', 'Manager'],
    navTabs: [{ label: 'Dashboard', tab: 'dashboard' }, { label: 'Overtime Reports', tab: 'ot-reports' }],
    blocks: blocks({
      'Overview': [
        'This module turns HRMS transaction data into summaries, reports, and decision-ready views.',
        'It exists so HR and leadership can understand attendance patterns, payroll costs, leave usage, overtime trends, and workforce distribution.',
        'Business value: reliable reports reduce manual spreadsheet work and support faster workforce decisions.',
      ],
      'Who Uses This': [
        'Admins view company-wide operational and setup health.',
        'HR analyzes employees, attendance, leave, imports, and payroll readiness.',
        'Managers review team metrics when scoped permissions are enabled.',
        'Finance users consume payroll and overtime reports where access is granted.',
      ],
      'Prerequisites': [
        'Transactional data must exist in the relevant modules.',
        'Employees must be assigned to correct departments and branches for useful grouping.',
        'Payroll reports require selected payroll run and completed payroll setup.',
        'Exports may require role permission and an active data range filter.',
      ],
      'Key Features': [
        'Dashboard overview cards and recent activity.',
        'Attendance records filtering and export-ready review.',
        'Overtime records and monthly reports.',
        'Payroll reports and payslip-related outputs.',
        'Leave balances and ledger for absence analytics.',
      ],
      'How It Works (Conceptual Flow)': [
        'Reports read from module records rather than separate manual input.',
        'Employee master data supplies department, branch, role, and status dimensions.',
        'Attendance, leave, overtime, and payroll records supply time-based metrics.',
        'Filters narrow the data by date, employee, department, branch, status, or payroll run.',
      ],
      'Step-by-Step Usage': [
        'Open Dashboard for high-level company status.',
        'Open the relevant module report view, such as Overtime > Overtime Reports or Payroll > Reports.',
        'Select date range, month, employee, department, or status filters.',
        'Review totals and exception rows before exporting.',
        'Click the available export or download action; expected result is a file or report generated from the filtered data.',
      ],
      'Common Use Cases': [
        'Monthly attendance exception review before payroll.',
        'Department-wise overtime analysis.',
        'Leave balance audit before year-end rollover.',
        'Payroll report export after finalization.',
      ],
      'Edge Cases & Rules': [
        'Reports can look incomplete if setup data is missing or employees are misclassified.',
        'Draft payroll runs may not match finalized payroll reports.',
        'Manual attendance corrections should be completed before attendance reports are trusted.',
        'Date range and timezone choices affect daily attendance and night-shift reporting.',
      ],
      'Errors & Troubleshooting': [
        'Report is empty: widen date range and confirm records exist in the source module.',
        'Totals do not match expectation: check filters, inactive employees, manual adjustments, and finalized status.',
        'Export disabled: confirm role permission and required selected run or date range.',
        'Department totals wrong: audit employee department assignments.',
      ],
      'Best Practices': [
        'Agree on reporting cutoff dates before payroll operations.',
        'Export reports after final approval and archive them consistently.',
        'Use filters to investigate exceptions before sharing broad summaries.',
        'Clean employee master data regularly because reports depend on it.',
      ],
    }),
  },
  {
    id: 'roles-permissions',
    title: 'Roles & Permissions',
    summary: 'Access control model that decides which modules, records, and actions each user can use.',
    category: 'Security',
    icon: ShieldCheck,
    audience: ['Admin', 'HR', 'Manager', 'Employee'],
    navTabs: [{ label: 'My Profile', tab: 'profile' }],
    blocks: blocks({
      'Overview': [
        'This module governs what each user can view and do inside the HRMS.',
        'It exists to protect sensitive data such as salary, tax, personal information, and administrative setup.',
        'Business value: correct permissions reduce data leaks, accidental edits, and approval conflicts.',
      ],
      'Who Uses This': [
        'Admins assign and review access levels.',
        'HR users operate HR workflows within assigned permission boundaries.',
        'Managers approve or review team workflows where manager permissions exist.',
        'Employees access their own self-service data and requests.',
      ],
      'Prerequisites': [
        'Each user must have a role in their account or employee profile.',
        'Route and backend permissions must both recognize the role.',
        'Company access must be assigned for users who work across companies.',
        'Sensitive roles should be reviewed before payroll or employee data access is granted.',
      ],
      'Key Features': [
        'Role-aware routing for protected pages.',
        'Admin and HR access to core workforce modules.',
        'Restricted Payroll route for admin and HR roles in this app.',
        'Profile visibility for current role and employment context.',
        'Super admin separation from HR dashboard.',
      ],
      'How It Works (Conceptual Flow)': [
        'Login token contains role claims.',
        'Frontend route guards allow or block pages based on those claims.',
        'Backend APIs should enforce the same permissions for data security.',
        'Employee profile role and company membership determine operational access and visible actions.',
      ],
      'Step-by-Step Usage': [
        'Open Employees > Employee Directory and select the employee who needs access review.',
        'Open the profile or edit drawer and verify role authority.',
        'Assign the correct role according to responsibility.',
        'Ask the user to sign out and sign in again if token claims need refreshing.',
        'Open My Profile as that user to confirm the expected role is visible.',
      ],
      'Common Use Cases': [
        'Give HR access to employee and attendance management.',
        'Limit payroll actions to admins or approved HR users.',
        'Convert an employee to manager access after promotion.',
        'Remove access after employee exit.',
      ],
      'Edge Cases & Rules': [
        'Changing a role may not affect an already-issued token until the user signs in again.',
        'Frontend hiding is not enough; backend permissions must enforce real security.',
        'Super admin users are intentionally redirected away from HR dashboard.',
        'Employees should not receive HR setup or payroll administration access by default.',
      ],
      'Errors & Troubleshooting': [
        'User cannot open a page: confirm role, route restrictions, backend permissions, and fresh login.',
        'User sees too much data: remove elevated role and invalidate or refresh session.',
        'Payroll inaccessible: confirm user role is admin or HR.',
        'Role display looks wrong: verify employee profile and token claims are aligned.',
      ],
      'Best Practices': [
        'Follow least privilege: grant only the access needed for the job.',
        'Review permissions during onboarding, transfer, promotion, and exit.',
        'Keep payroll and employee deletion permissions tightly controlled.',
        'Audit role changes before monthly payroll and compliance reviews.',
      ],
    }),
  },
  {
    id: 'bulk-upload-system',
    title: 'Bulk Upload System',
    summary: 'Imports employees and attendance data from CSV or external biometric files with validation, preview, queueing, and error review.',
    category: 'Data',
    icon: Upload,
    audience: ['Admin', 'HR'],
    navTabs: [{ label: 'Employee Bulk Import', tab: 'employees-import-queue' }, { label: 'Attendance Upload', tab: 'attendance-upload' }],
    blocks: blocks({
      'Overview': [
        'This module lets HR create or update many records from spreadsheet-style files.',
        'It exists to speed up initial onboarding and recurring imports from external attendance devices.',
        'Business value: bulk upload saves hours of manual data entry while preserving validation and auditability.',
      ],
      'Who Uses This': [
        'Admins import initial workforce records during implementation.',
        'HR imports employee batches, reviews failed rows, and monitors import jobs.',
        'Attendance admins upload biometric attendance files when devices are outside the live app flow.',
      ],
      'Prerequisites': [
        'Required setup lookups must exist before employee import: department, branch, designation, employment type, grade, and group where used.',
        'CSV columns must match the system template.',
        'User must have permission to import the selected data type.',
        'Attendance imports require employee identifiers that match existing employee records.',
      ],
      'Key Features': [
        'Employee CSV import preview and validation.',
        'Import queue with job status history.',
        'Row-level errors and downloadable error file where supported.',
        'Bulk invite and employee account activation support.',
        'Biometric attendance upload for external punch devices.',
      ],
      'How It Works (Conceptual Flow)': [
        'User uploads file, system parses rows, validates each field, and maps lookup names to IDs.',
        'Valid rows are queued for processing; failed rows are reported with reasons.',
        'Employee import creates employee profiles and may prepare invite actions.',
        'Attendance upload maps punch rows to employees and dates, then creates or updates attendance records according to import rules.',
      ],
      'Step-by-Step Usage': [
        'Go to Employees > Bulk Import for employee data or Attendance > Import from Biometric for attendance data.',
        'Download or open the expected template if available.',
        'Fill required columns and keep lookup names exactly aligned with HR Setup records.',
        'Upload the CSV or supported file.',
        'Review preview results; expected result is clear valid and invalid row counts.',
        'Submit the import job and monitor queue status.',
        'Download errors, correct the file, and re-upload failed rows if needed.',
      ],
      'Common Use Cases': [
        'Import the first 500 employees during go-live.',
        'Bulk add seasonal workers or interns.',
        'Upload attendance data from biometric hardware.',
        'Fix failed import rows and rerun only corrected records.',
      ],
      'Edge Cases & Rules': [
        'Lookup names must match exactly; extra spaces and spelling differences can fail rows.',
        'Duplicate emails or employee codes should be rejected or flagged.',
        'Partial imports can create some records while others fail; always review results.',
        'Attendance imports must avoid creating duplicate punches for the same employee and timestamp.',
      ],
      'Errors & Troubleshooting': [
        'Invalid template: compare column names with the system template and remove unsupported columns.',
        'Lookup not found: create the missing setup value or correct spelling in the file.',
        'Duplicate employee: check email, employee code, and existing employee directory.',
        'Attendance row not matched: verify employee code or device ID mapping.',
      ],
      'Best Practices': [
        'Import a small sample first before uploading the full file.',
        'Keep a clean source file and a separate corrected-errors file.',
        'Do not edit exported error files without preserving row identifiers.',
        'Run imports before business cutoff dates so HR has time to fix failures.',
      ],
    }),
  },
  {
    id: 'settings-configuration',
    title: 'Settings & Configuration',
    summary: 'Administrative configuration for workspace preferences, payroll settings, attendance policy setup, integrations, and system behavior.',
    category: 'Administration',
    icon: Settings,
    audience: ['Admin', 'HR'],
    navTabs: [{ label: 'Workspace Settings', tab: 'workspace-settings' }, { label: 'Payroll Settings', tab: 'payroll' }],
    blocks: blocks({
      'Overview': [
        'This module contains configurable rules and preferences that shape how the HRMS behaves.',
        'It exists because each company has different attendance rules, leave policies, payroll structures, calendars, and workspace practices.',
        'Business value: configurable settings let the product match company policy without code changes.',
      ],
      'Who Uses This': [
        'Admins own system-wide configuration and sensitive finance settings.',
        'HR users manage operational settings such as leave, attendance, shifts, and workspace preferences.',
        'Finance users may manage payroll settings if given access.',
      ],
      'Prerequisites': [
        'Admin or HR permission is required for most settings.',
        'Company setup should be completed before fine-tuning advanced configuration.',
        'Policy decisions must be approved internally before being encoded in settings.',
        'Integrations require valid external account authorization where applicable.',
      ],
      'Key Features': [
        'Workspace settings for shared collaboration environment.',
        'Payroll settings for salary structures and tax profiles.',
        'Attendance setup through shift types, shift locations, holiday calendars, and assignments.',
        'Leave setup through periods, policies, holiday lists, and allocations.',
        'Integration settings such as Google calendar where enabled.',
      ],
      'How It Works (Conceptual Flow)': [
        'Settings produce rules that downstream modules use during transactions.',
        'Shift settings affect attendance calculations; leave settings affect balances; payroll settings affect salary output; workspace settings affect collaboration behavior.',
        'Changing a setting can affect future records immediately, while historical records should remain auditable.',
        'Effective dates and scoped policies help manage changes without rewriting history.',
      ],
      'Step-by-Step Usage': [
        'Identify the business policy you need to configure.',
        'Open the matching settings area: HR Setup, Shifts, Leave, Payroll, or Workspace Settings.',
        'Create or edit the configuration record.',
        'Save and test with one employee or one sample transaction.',
        'Review downstream modules to confirm the expected result appears.',
        'Communicate the change to affected HR users or employees before rollout.',
      ],
      'Common Use Cases': [
        'Change attendance grace period for a shift type.',
        'Create a new leave policy for probation employees.',
        'Update salary structure percentages for a new compensation plan.',
        'Connect or disconnect calendar integration.',
      ],
      'Edge Cases & Rules': [
        'Policy changes can have payroll impact; coordinate changes with cutoff dates.',
        'Historical edits should be avoided when effective dating is available.',
        'Deleting settings used by active employees can break forms, reports, or calculations.',
        'Integration settings may fail if external authorization expires.',
      ],
      'Errors & Troubleshooting': [
        'Setting not applying: confirm employee assignment, effective date, scope, and saved status.',
        'Unexpected payroll result after change: review salary structure version and payroll run recalculation.',
        'Attendance still using old rule: check employee active shift assignment and shift type.',
        'Integration disconnected: reauthorize external account and refresh selected calendars.',
      ],
      'Best Practices': [
        'Make configuration changes in planned windows, especially before payroll cutoff.',
        'Test policy changes with a small employee set before broad rollout.',
        'Use clear names and descriptions for every policy or setting.',
        'Keep a change log for settings that affect pay, leave, or compliance.',
      ],
    }),
  },
]

export const systemFlows: HelpFlow[] = [
  {
    title: 'Global System Flow',
    icon: Activity,
    points: [
      'Company setup creates departments, branches, designations, employment types, grades, groups, shifts, leave policies, and payroll settings.',
      'Employees connect those setup records to real people.',
      'Attendance and leave create daily operational records for each employee.',
      'Overtime and payroll consume attendance, leave, salary, and policy data.',
      'Reports and notifications surface exceptions, approvals, and business-ready summaries.',
    ],
  },
  {
    title: 'First-Time Admin Journey',
    icon: CheckCircle2,
    points: [
      'Sign in, select company, and complete onboarding.',
      'Create HR setup lookups before importing employees.',
      'Configure shifts, locations, leave rules, and payroll settings.',
      'Import or add employees, send invites, and verify profiles.',
      'Run a pilot day for attendance, leave, and payroll readiness before go-live.',
    ],
  },
  {
    title: 'Employee First Login Flow',
    icon: Users,
    points: [
      'Employee receives invite and creates login access.',
      'Employee opens profile and confirms personal and employment details.',
      'Employee installs PWA if attendance is mobile-based.',
      'Employee grants location or camera permissions only when required by policy.',
      'Employee uses Attendance, Leave, Payslip, and request flows according to assigned permissions.',
    ],
  },
  {
    title: 'HR Daily Workflow',
    icon: FileSpreadsheet,
    points: [
      'Review dashboard and attendance exceptions first.',
      'Resolve missed punch-outs and correction requests.',
      'Approve or reject leave and overtime requests.',
      'Update employee changes such as transfers, exits, or invite issues.',
      'Check reports before payroll cutoff and export required summaries.',
    ],
  },
]

export const uxImprovements = [
  'Use the left sidebar as a persistent module index with category labels and active section highlighting.',
  'Use search to filter modules by title, category, summary, role, and documentation body.',
  'Keep each documentation block collapsible so long help content remains scannable.',
  'Expose quick action buttons that deep-link users from documentation into the operational module.',
  'Add future anchors for video walkthroughs, downloadable templates, and policy-specific examples without changing the page structure.',
]


