import type { HowToFlow } from './helpTypes'

export const howToFlows: HowToFlow[] = [
  {
    id: 'setup-attendance',
    title: 'Set Up the Complete Attendance Module',
    summary: 'Configure HR setup, locations, shifts, employee assignments, attendance capture, corrections, and daily review.',
    owner: 'Admin or HR',
    outcome: 'Employees can clock in and clock out, HR can review records, and attendance data is ready for overtime and payroll.',
    prerequisites: [
      'Company workspace is active.',
      'Admin or HR user can access HR Setup, Employees, Shifts, and Attendance.',
      'Employee list, office locations, shift timings, grace period, and attendance policy are finalized.',
    ],
    steps: [
      {
        title: 'Create departments and branches',
        detail: 'Go to HR Setup > Departments and HR Setup > Branches. Add every department and physical branch that will appear on employee profiles and reports.',
        expectedResult: 'Department and branch options are available when creating or importing employees.',
        tab: 'departments',
      },
      {
        title: 'Create designations, employment types, grades, and groups',
        detail: 'Complete the remaining HR Setup records before importing employees. Use groups for teams with different policies, such as field staff or remote workers.',
        expectedResult: 'Employee profiles can be completed without missing lookup values.',
        tab: 'designations',
      },
      {
        title: 'Create shift locations',
        detail: 'Go to Shifts > Shift Locations. Add one location per office, site, or remote attendance zone with correct latitude, longitude, and radius.',
        expectedResult: 'The system can validate whether an employee is inside the allowed attendance location.',
        tab: 'shift-locations',
      },
      {
        title: 'Create shift types',
        detail: 'Go to Shifts > Shift Types. Define start time, end time, break minutes, grace minutes, color, and night-shift behavior.',
        expectedResult: 'The system knows how to calculate late marks, work hours, and night-shift dates.',
        tab: 'shift-types',
      },
      {
        title: 'Add or import employees',
        detail: 'Go to Employees > Employee Directory for manual creation or Employees > Bulk Import for CSV upload. Confirm every attendance employee is active.',
        expectedResult: 'Employees exist in the directory and can receive portal invites.',
        tab: 'employees',
      },
      {
        title: 'Assign shifts and locations',
        detail: 'Go to Shifts > Shift Schedules. Create schedules and assign employees to them with effective dates.',
        expectedResult: 'Each employee has one valid attendance rule for the work date.',
        tab: 'shift-schedules',
      },
      {
        title: 'Verify roster and setup warnings',
        detail: 'Open Shifts > Roster and Attendance views. Fix employees with missing shifts, missing locations, or overlapping assignments.',
        expectedResult: 'Roster shows the expected employees and setup warnings are resolved before go-live.',
        tab: 'roster',
      },
      {
        title: 'Invite employees and test clock-in',
        detail: 'Send portal invites. Ask a pilot employee to sign in, allow location permission, clock in, and clock out.',
        expectedResult: 'Attendance > Records shows a completed test record with correct time and location data.',
        tab: 'attendance-records',
      },
      {
        title: 'Set daily review process',
        detail: 'HR should review Attendance Records and Attendance Adjustments daily for missed punch-outs, late arrivals, and correction requests.',
        expectedResult: 'Attendance data stays clean before overtime calculation and payroll cutoff.',
        tab: 'attendance-requests',
      },
    ],
    checks: [
      'Every attendance employee has one active schedule assignment.',
      'Each schedule assignment has both shift type and shift location.',
      'Night shifts are marked correctly.',
      'Test records appear in Attendance Records.',
      'HR knows where to review adjustments and biometric imports.',
    ],
  },
  {
    id: 'setup-leaves',
    title: 'Set Up the Complete Leave Module',
    summary: 'Create the leave year, holidays, leave types, policies, assignments, allocations, balances, and operational review process.',
    owner: 'Admin or HR',
    outcome: 'Employees have accurate leave balances and HR can manage requests, block lists, comp-off, encashment, and ledger history.',
    prerequisites: [
      'Employees are created and assigned to the correct department, branch, and group.',
      'Company leave policy is approved by HR leadership.',
      'Holiday calendar, carry-forward, accrual, and approval rules are finalized.',
    ],
    steps: [
      {
        title: 'Create the leave period',
        detail: 'Go to Leave > Leave Periods. Add the annual, calendar-year, or fiscal-year period used for balances and requests.',
        expectedResult: 'Leave transactions have a date container for the active leave cycle.',
        tab: 'leave-periods',
      },
      {
        title: 'Create holiday lists',
        detail: 'Go to Leave > Holiday Lists. Add public holidays, company holidays, and location-specific holidays if applicable.',
        expectedResult: 'Holidays can be excluded or handled correctly during leave calculation.',
        tab: 'holiday-lists',
      },
      {
        title: 'Create leave types',
        detail: 'Go to Leave > Leave Types. Add Annual Leave, Sick Leave, Casual Leave, Unpaid Leave, Maternity Leave, Paternity Leave, or other company-specific types.',
        expectedResult: 'Employees can request the correct leave category.',
        tab: 'leave-types',
      },
      {
        title: 'Create leave policies',
        detail: 'Go to Leave > Leave Policies. Define entitlement rules, carry-forward, accrual, maximum consecutive days, approval behavior, and linked holiday list.',
        expectedResult: 'The system knows how each leave type should behave.',
        tab: 'leave-policies',
      },
      {
        title: 'Assign policies',
        detail: 'Go to Leave > Policy Assignments. Assign policies to employees or employee groups with effective dates.',
        expectedResult: 'Employees are connected to the correct leave rule set.',
        tab: 'leave-policy-assignments',
      },
      {
        title: 'Allocate opening balances',
        detail: 'Go to Leave > Leave Allocations. Add new leaves and carry-forward days for each employee and leave type.',
        expectedResult: 'Leave Balances shows available days for each employee.',
        tab: 'leave-allocations',
      },
      {
        title: 'Configure restrictions and special cases',
        detail: 'Use Leave Block Lists for blackout dates, Compensatory Leave for approved extra work, and Leave Encashment for payout workflows.',
        expectedResult: 'HR can handle real-world absence rules without manual spreadsheets.',
        tab: 'leave-block-lists',
      },
      {
        title: 'Audit balances and ledger',
        detail: 'Open Leave Balances and Leave Ledger. Confirm allocations, approvals, encashments, and corrections are reflected correctly.',
        expectedResult: 'HR has a reliable audit trail before employees begin requesting leave.',
        tab: 'leave-ledger',
      },
    ],
    checks: [
      'Every active employee has an applicable leave policy.',
      'Every leave type has opening allocation where required.',
      'Holiday list dates match the leave period.',
      'Leave Balances match HR policy.',
      'Leave Ledger shows a clean audit trail.',
    ],
  },
  {
    id: 'setup-payroll',
    title: 'Set Up the Complete Payroll Module',
    summary: 'Prepare salary structures, tax profiles, employee salary data, attendance inputs, payroll runs, reports, and payslip output.',
    owner: 'Admin, HR, or Payroll Admin',
    outcome: 'Payroll can be calculated, reviewed, finalized, reported, and used for payslips with fewer manual corrections.',
    prerequisites: [
      'Employee records are active and include joining dates.',
      'Departments, branches, grades, and salary fields are accurate.',
      'Attendance, leave without pay, overtime, tax, and statutory deduction policies are finalized.',
    ],
    steps: [
      {
        title: 'Review employee master data',
        detail: 'Go to Employees > Employee Directory. Confirm active status, joining date, department, branch, grade, salary, and statutory details.',
        expectedResult: 'Payroll has clean employee inputs before calculation.',
        tab: 'employees',
      },
      {
        title: 'Configure salary structures',
        detail: 'Go to Payroll > Settings. Create salary structures such as Standard CTC, Worker Pay, or Executive Salary with component percentages.',
        expectedResult: 'The system can split gross pay into basic, HRA, allowances, PF, ESI, and other components.',
        tab: 'payroll',
      },
      {
        title: 'Configure tax profiles',
        detail: 'Create tax profiles for the applicable regime, slabs, deductions, exemptions, and statutory rules.',
        expectedResult: 'Payroll can calculate tax and statutory deductions consistently.',
        tab: 'payroll',
      },
      {
        title: 'Assign payroll setup to employees',
        detail: 'Attach salary structure and tax profile to each payroll employee from employee or payroll setup screens.',
        expectedResult: 'Employees are eligible for payroll run inclusion.',
        tab: 'employees',
      },
      {
        title: 'Close attendance and leave inputs',
        detail: 'Before payroll cutoff, resolve missed punch-outs, unpaid leaves, overtime approvals, and attendance corrections.',
        expectedResult: 'Payable days, overtime, and unpaid leave are accurate.',
        tab: 'attendance-records',
      },
      {
        title: 'Create payroll run',
        detail: 'Go to Payroll. Create a new run for the target month or pay period and review included employees.',
        expectedResult: 'Payroll draft is created with calculated gross, deductions, and net pay.',
        tab: 'payroll',
      },
      {
        title: 'Review exceptions and recalculate',
        detail: 'Fix missing salary setup, incorrect employee status, wrong attendance inputs, or tax profile gaps. Recalculate if required.',
        expectedResult: 'Payroll exception list is resolved before finalization.',
        tab: 'payroll',
      },
      {
        title: 'Finalize and export',
        detail: 'Finalize the run only after approval. Generate reports and payslips from Payroll > Reports.',
        expectedResult: 'Payroll period is locked and reports are ready for finance and employees.',
        tab: 'payroll',
      },
    ],
    checks: [
      'All payroll employees have salary structure and tax profile.',
      'Attendance and leave exceptions are closed before cutoff.',
      'Draft totals are reviewed before finalization.',
      'Finalized payroll reports are exported and archived.',
      'Corrections after finalization follow an adjustment process.',
    ],
  },
  {
    id: 'setup-employees',
    title: 'Set Up Employees from Scratch',
    summary: 'Prepare lookup data, create or import employees, send invites, verify profiles, and connect employees to operating modules.',
    owner: 'Admin or HR',
    outcome: 'Employees are ready for login, attendance, leave, reporting, and payroll workflows.',
    prerequisites: [
      'HR setup values are defined.',
      'Employee source data is clean and approved.',
      'Invite email addresses are valid.',
    ],
    steps: [
      {
        title: 'Complete HR Setup first',
        detail: 'Create departments, branches, designations, employment types, employee grades, and employee groups.',
        expectedResult: 'Employee profiles and CSV imports can reference valid lookup values.',
        tab: 'departments',
      },
      {
        title: 'Choose manual entry or bulk import',
        detail: 'Use manual Add Employee for small or sensitive batches. Use Bulk Import for large onboarding batches.',
        expectedResult: 'HR uses the correct creation method for the volume and risk.',
        tab: 'employees',
      },
      {
        title: 'Create employees',
        detail: 'Enter personal, contact, joining, department, salary, emergency, education, experience, and exit data where applicable.',
        expectedResult: 'Employee Directory shows accurate active employee records.',
        tab: 'employees',
      },
      {
        title: 'Send portal invites',
        detail: 'Send or resend invites for employees who need self-service access.',
        expectedResult: 'Employees can activate login and access their profile.',
        tab: 'employees',
      },
      {
        title: 'Connect employees to modules',
        detail: 'Assign shifts for attendance, policies for leave, and salary/tax profiles for payroll.',
        expectedResult: 'Employees are operational across all required HRMS modules.',
        tab: 'shift-assignments',
      },
    ],
    checks: [
      'No employee has missing department, branch, designation, or employment type.',
      'Portal invite status is tracked.',
      'Payroll employees have salary setup.',
      'Attendance employees have schedule assignment.',
      'Leave employees have policy and allocation.',
    ],
  },
  {
    id: 'setup-company-go-live',
    title: 'Prepare a Company for Go-Live',
    summary: 'A complete implementation flow for first-time Admins before employees start using the HRMS.',
    owner: 'Admin',
    outcome: 'The company is ready for real employee transactions with fewer setup gaps.',
    prerequisites: [
      'Company account is created.',
      'Admin has login access.',
      'HR, finance, and operations have approved the launch policies.',
    ],
    steps: [
      {
        title: 'Complete company onboarding',
        detail: 'Use the onboarding checklist to understand setup progress and open required modules.',
        expectedResult: 'Admin knows which setup areas are complete and which are pending.',
        tab: 'dashboard',
      },
      {
        title: 'Create core master data',
        detail: 'Set up departments, branches, designations, employment types, grades, and groups.',
        expectedResult: 'The company has clean organizational structure.',
        tab: 'departments',
      },
      {
        title: 'Configure attendance and leave',
        detail: 'Create shift locations, shift types, shift schedules, leave periods, leave policies, and allocations.',
        expectedResult: 'Employees can record attendance and request leave after launch.',
        tab: 'shift-types',
      },
      {
        title: 'Configure payroll if used',
        detail: 'Create salary structures, tax profiles, payroll settings, and employee payroll assignments.',
        expectedResult: 'Payroll can be tested before the first real payroll cycle.',
        tab: 'payroll',
      },
      {
        title: 'Run pilot validation',
        detail: 'Test one employee through login, clock-in, leave request, attendance correction, and payroll draft.',
        expectedResult: 'Admin confirms the end-to-end workflow works before broad rollout.',
        tab: 'help',
      },
      {
        title: 'Invite employees',
        detail: 'Send invites after setup is verified and communicate login, attendance, and request expectations.',
        expectedResult: 'Employees can begin using HRMS with fewer support issues.',
        tab: 'employees',
      },
    ],
    checks: [
      'Onboarding warnings are resolved.',
      'Pilot employee workflow is successful.',
      'Employees receive invite instructions.',
      'HR knows the daily review process.',
      'Payroll cutoff and approval process is documented.',
    ],
  },
  {
    id: 'setup-bulk-upload',
    title: 'Use Bulk Upload Safely',
    summary: 'Import employees or attendance data with template validation, preview review, queue monitoring, and error correction.',
    owner: 'Admin or HR',
    outcome: 'Large data imports are completed with fewer duplicates and cleaner error recovery.',
    prerequisites: [
      'Import template is available.',
      'Lookup values already exist in HR Setup.',
      'User has import permission.',
    ],
    steps: [
      {
        title: 'Download or confirm template',
        detail: 'Open Employees > Bulk Import or Attendance > Import from Biometric. Use the expected column format.',
        expectedResult: 'Import file uses system-compatible headers.',
        tab: 'employees-import-queue',
      },
      {
        title: 'Prepare source data',
        detail: 'Clean employee codes, emails, dates, departments, branches, designations, and attendance device identifiers.',
        expectedResult: 'File values match existing system records.',
        tab: 'employees-import-queue',
      },
      {
        title: 'Upload and preview',
        detail: 'Upload the file and review valid rows, failed rows, warnings, and automatic corrections.',
        expectedResult: 'HR knows which rows will import and which need correction.',
        tab: 'employees-import-queue',
      },
      {
        title: 'Submit import job',
        detail: 'Start the import and monitor the queue until it reaches success or failed status.',
        expectedResult: 'Processed rows appear in the target module.',
        tab: 'employees-import-queue',
      },
      {
        title: 'Fix failed rows',
        detail: 'Download error details, correct only failed records, and re-upload a clean correction file.',
        expectedResult: 'Failed rows are resolved without duplicating successful records.',
        tab: 'employees-import-queue',
      },
    ],
    checks: [
      'Lookup names match exactly.',
      'Duplicate emails and employee codes are resolved.',
      'Successful rows are not re-imported unnecessarily.',
      'Error files are archived for audit.',
      'Attendance imports are checked for duplicate punches.',
    ],
  },
]
